kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multicat
nodes:
  - role: control-plane
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: C:\Users\akahi\.docker\config.json  # TODO: Replace with Helm
    extraPortMappings:
      - containerPort: 31001
        hostPort: 31001
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: C:\Users\akahi\.docker\config.json  # TODO: Replace with Helm